name: Build & Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest  # Change this to ubuntu-latest if you want the latest version of Ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v2  # This is fine, v2 is the latest stable version
          
      - name: Setup Node
        uses: actions/setup-node@v3  # Updated to the latest stable version
        with:
          node-version: '20'  # Updated Node.js version (recommended to use a LTS version like 16.x)

      - name: Cache
        uses: actions/cache@v3  # Updated to the latest version
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: |
          pwd
          ls
          npm ci
          npm run build
          ls
          pwd

        shell: bash

      # - name: Build
      #   run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # base_branch: master
          branch: gh-pages
          folder: dist/spa
